#!/usr/bin/env bash
# Interactive setup for dual Azure Blob storage (.cloud-vfs/config.env).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib-azure.sh
source "$SCRIPT_DIR/lib-azure.sh"
require_az

ROOT="$(find_project_root)"
CFG_DIR="$ROOT/.cloud-vfs"
CFG="$CFG_DIR/config.env"
mkdir -p "$CFG_DIR"

echo "=== cloud-vfs setup ==="
echo "Project: $ROOT"
echo "Two blob accounts (not synced): local archive + cloud staging"
echo

read -r -p "Local archive region (e.g. centralindia, eastus, westeurope): " LOCAL_LOC
read -r -p "Local archive resource group [cloud-vfs-local-rg]: " LOCAL_RG
LOCAL_RG=${LOCAL_RG:-cloud-vfs-local-rg}
read -r -p "Local storage account name (globally unique): " LOCAL_ACCOUNT
read -r -p "Local container name [data]: " LOCAL_CONTAINER
LOCAL_CONTAINER=${LOCAL_CONTAINER:-data}

echo
read -r -p "Cloud staging region (e.g. westeurope, eastus2): " RUNPOD_LOC
read -r -p "Cloud staging resource group [cloud-vfs-staging-rg]: " RUNPOD_RG
RUNPOD_RG=${RUNPOD_RG:-cloud-vfs-staging-rg}
read -r -p "Cloud staging storage account name: " RUNPOD_ACCOUNT
read -r -p "Cloud staging container name [data]: " RUNPOD_CONTAINER
RUNPOD_CONTAINER=${RUNPOD_CONTAINER:-data}

cat > "$CFG" <<EOF
# Generated by cloud-vfs-setup — edit as needed.

AZ_LOCAL_RG="$LOCAL_RG"
AZ_LOCAL_LOC="$LOCAL_LOC"
AZ_LOCAL_STORAGE_ACCOUNT="$LOCAL_ACCOUNT"
AZ_LOCAL_CONTAINER="$LOCAL_CONTAINER"

AZ_RUNPOD_RG="$RUNPOD_RG"
AZ_RUNPOD_LOC="$RUNPOD_LOC"
AZ_RUNPOD_STORAGE_ACCOUNT="$RUNPOD_ACCOUNT"
AZ_RUNPOD_CONTAINER="$RUNPOD_CONTAINER"

AZ_BLOB_DATA_PREFIX="data"
AZ_BLOB_CODE_PREFIX="code"
AZ_BLOB_CHECKPOINTS_PREFIX="checkpoints"
EOF

echo "Wrote $CFG"
read -r -p "Provision both storage accounts now? [y/N] " ans
if [[ "$ans" =~ ^[Yy]$ ]]; then
  "$SCRIPT_DIR/provision-azure.sh"
fi

echo
echo "Next: edit $CFG_DIR/manifest.json, then run: cloud-vfs status"
