#!/usr/bin/env bash
# Interactive setup — writes .cloud-vfs/config.env
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib-azure.sh
source "$SCRIPT_DIR/lib-azure.sh"
require_az

ROOT="$(_find)"
CFG_DIR="$ROOT/.cloud-vfs"
CFG="$CFG_DIR/config.env"
mkdir -p "$CFG_DIR"

echo "=== cloud-vfs setup ==="
echo "Project: $ROOT"
echo
echo "You can use one Azure storage account or two independent accounts."
echo "  • Local archive  — long-term offload catalog (near you)"
echo "  • Remote staging — optional second account (e.g. near cloud compute)"
echo

read -r -p "Local archive region (e.g. eastus, westeurope): " LOCAL_LOC
read -r -p "Local resource group [cloud-vfs-local-rg]: " LOCAL_RG
LOCAL_RG=${LOCAL_RG:-cloud-vfs-local-rg}
read -r -p "Local storage account name (globally unique): " LOCAL_ACCOUNT
read -r -p "Local container name [data]: " LOCAL_CONTAINER
LOCAL_CONTAINER=${LOCAL_CONTAINER:-data}

echo
read -r -p "Use a second (remote) storage account? [y/N] " use_remote
if [[ "$use_remote" =~ ^[Yy]$ ]]; then
  read -r -p "Remote region: " REMOTE_LOC
  read -r -p "Remote resource group [cloud-vfs-remote-rg]: " REMOTE_RG
  REMOTE_RG=${REMOTE_RG:-cloud-vfs-remote-rg}
  read -r -p "Remote storage account name: " REMOTE_ACCOUNT
  read -r -p "Remote container name [data]: " REMOTE_CONTAINER
  REMOTE_CONTAINER=${REMOTE_CONTAINER:-data}
else
  REMOTE_LOC="$LOCAL_LOC"
  REMOTE_RG="$LOCAL_RG"
  REMOTE_ACCOUNT="$LOCAL_ACCOUNT"
  REMOTE_CONTAINER="$LOCAL_CONTAINER"
fi

cat > "$CFG" <<EOF
# Generated by cloud-vfs-setup

AZ_LOCAL_RG="$LOCAL_RG"
AZ_LOCAL_LOC="$LOCAL_LOC"
AZ_LOCAL_STORAGE_ACCOUNT="$LOCAL_ACCOUNT"
AZ_LOCAL_CONTAINER="$LOCAL_CONTAINER"

AZ_REMOTE_RG="$REMOTE_RG"
AZ_REMOTE_LOC="$REMOTE_LOC"
AZ_REMOTE_STORAGE_ACCOUNT="$REMOTE_ACCOUNT"
AZ_REMOTE_CONTAINER="$REMOTE_CONTAINER"

AZ_BLOB_DATA_PREFIX="data"
AZ_BLOB_CODE_PREFIX="code"
AZ_BLOB_CHECKPOINTS_PREFIX="checkpoints"
EOF

echo "Wrote $CFG"
read -r -p "Provision storage account(s) now? [y/N] " ans
if [[ "$ans" =~ ^[Yy]$ ]]; then
  "$SCRIPT_DIR/provision-azure.sh"
fi

echo
echo "Next: edit $CFG_DIR/manifest.json, then run: cloud-vfs status"
